<template>
  <div class="privacy-container">
    <h1>Privacy Policy for Sussy Courses</h1>
    <div class="heading-divider"></div> <!-- Divider line below the main heading -->
    <h2>Privacy Policy</h2>
    <p>Last updated: November 08, 2024</p>
    <p>
      This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your
      information when You use the Service and tells You about Your privacy rights and how the law protects You.
    </p>
    <p>
      We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
      and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help
      of the <a
        href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank">Privacy Policy Generator</a>.</p>

    <h2>Interpretation and Definitions</h2>
    <h3>Interpretation</h3>
    <p>
      The words of which the initial letter is capitalized have meanings defined under the following conditions. The
      following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
    </p>

    <h3>Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
      <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
      <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
      <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to SUSSY Courses.</li>
      <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
      <li><strong>Country</strong> refers to: Hong Kong SAR China</li>
      <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
      <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
      <li><strong>Service</strong> refers to the Website.</li>
      <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
      <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
      <li><strong>Website</strong> refers to SUSSY Courses, accessible from http://localhost:8080</li>
      <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>

    <h2>Collecting and Using Your Personal Data</h2>
    <h3>Types of Data Collected</h3>
    <h4>Personal Data</h4>
    <p>
      While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
    </p>
    <ul>
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Usage Data</li>
    </ul>

    <h4>Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service.</p>

    <h3>Tracking Technologies and Cookies</h3>
    <p>
      We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.
      Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and
      analyze Our Service.
    </p>

    <h4>Use of Your Personal Data</h4>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
      <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
      <li>To manage Your Account.</li>
      <li>To contact You.</li>
      <li>For business transfers.</li>
      <li>For other purposes: data analysis, identifying usage trends, etc.</li>
    </ul>

    <h2>Retention of Your Personal Data</h2>
    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>

    <h2>Transfer of Your Personal Data</h2>
    <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.</p>

    <h2>Delete Your Personal Data</h2>
    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>

    <h2>Disclosure of Your Personal Data</h2>
    <p>Under certain circumstances, the Company may disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>

    <h2>Security of Your Personal Data</h2>
    <p>The security of Your Personal Data is important to Us, but no method of transmission over the Internet or method of electronic storage is 100% secure.</p>

    <h2>Children's Privacy</h2>
    <p>Our Service does not address anyone under the age of 13.</p>

    <h2>Links to Other Websites</h2>
    <p>Our Service may contain links to other websites that are not operated by Us.</p>

    <h2>Changes to this Privacy Policy</h2>
    <p>We may update Our Privacy Policy from time to time.</p>

    <h2>Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, please contact us:</p>
    <ul>
      <li>By email: SUSSYCourses@gmail.com</li>
    </ul>
  </div>
</template>

<script setup>
// No additional JavaScript needed for static content.
</script>

<style scoped>
.privacy-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  font-family: Arial, sans-serif;
  color: #333;
  line-height: 1.6;
  text-align: left; /* Align content to the left */
}

.privacy-container h1 {
  font-size: 36px; /* Larger main title */
  color: #333;
  font-weight: bold;
  margin-top: 20px;
}

.heading-divider {
  width: 100%;
  height: 1px;
  background-color: #ddd;
  margin: 10px 0 30px; /* Adds spacing below the line */
}

.privacy-container h2 {
  font-size: 28px; /* Increased size for h2 */
  color: #333;
  margin-top: 30px;
}

.privacy-container h3 {
  font-size: 24px; /* Increased size for h3 */
  margin-top: 20px;
}

.privacy-container h4 {
  font-size: 20px; /* Increased size for h4 */
  margin-top: 20px;
}

.privacy-container p {
  margin-bottom: 15px;
}

.privacy-container ul {
  list-style-type: disc;
  padding-left: 20px;
}

.privacy-container li {
  margin-bottom: 10px;
}

.privacy-container a {
  color: #006DB5;
  text-decoration: none;
}
</style>
